# Generated by Django 4.2.16 on 2024-11-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='llm_response',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='status',
        ),
    ]
